Repository DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong, pull requests merged in 2023-11, with the labels that each got.

#32 [feat][#31] Color extension 생성
  AhnNyeong/AhnNyeong.xcodeproj/project.pbxproj
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Black/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Black/black-100.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Black/black-200.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Black/black-300.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Black/black-400.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Black/black-50.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Black/black-500.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Black/black-75.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Cal/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Cal/cal_today.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Cal/cal_weekday.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Coral/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Coral/coral-100.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Coral/coral-200.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Coral/coral-300.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Coral/coral-400.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Coral/coral-50.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Coral/coral-500.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Coral/coral-600.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Coral/coral-700.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Coral/coral-800.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/Coral/coral-900.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/White/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/White/white-100.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/White/white-200.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/White/white-300.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/White/white-400.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/White/white-50.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/White/white-500.colorset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/Color/White/white-75.colorset/Contents.json
  AhnNyeong/AhnNyeong/Color.swift
Labels: ✨feature

#41 [feat][#37] 알림 설정 화면 구현
  AhnNyeong/AhnNyeong/UI/SettingViews/SettingNotiView.swift
Labels: ✨feature

#39 [feat][#33] Text Modifier & Extension 생성
  AhnNyeong/AhnNyeong.xcodeproj/project.pbxproj
  AhnNyeong/AhnNyeong/TextModifier.swift
Labels: ✨feature

#43 [fix] project 파일 폴더링 에러 수정
  AhnNyeong/AhnNyeong.xcodeproj/project.pbxproj
Labels: 🚨hotfix

#44 [feat][#42] 설정의 사용 가이드, 서비스 약관 화면 구현
  AhnNyeong/AhnNyeong.xcodeproj/project.pbxproj
  AhnNyeong/AhnNyeong/ContentView.swift
  AhnNyeong/AhnNyeong/UI/SettingViews/DetailTermView.swift
  AhnNyeong/AhnNyeong/UI/SettingViews/SettingGuideView.swift
  AhnNyeong/AhnNyeong/UI/SettingViews/SettingMainView.swift
  AhnNyeong/AhnNyeong/UI/SettingViews/SettingNotiView.swift
  AhnNyeong/AhnNyeong/UI/SettingViews/SettingTermView.swift
Labels: ✨feature

#30 [feat][#29] 이용자 시작 뷰 생성
  AhnNyeong/AhnNyeong.xcodeproj/project.pbxproj
  AhnNyeong/AhnNyeong.xcodeproj/project.xcworkspace/xcuserdata/jaelyungkim.xcuserdatad/UserInterfaceState.xcuserstate
  AhnNyeong/AhnNyeong/Assets.xcassets/startDefault.imageset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/startDefault.imageset/startDefault.png
  AhnNyeong/AhnNyeong/Assets.xcassets/startPressed.imageset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/startPressed.imageset/startPressed.png
  AhnNyeong/AhnNyeong/TargetMainView.swift
  AhnNyeong/AhnNyeong/TextModifier.swift
  AhnNyeong/AhnNyeong/UI/TargetViews/TargetMainView.swift
Labels: ✨feature

#49 [fix][#29] 이용자 메인 뷰 ZStack 없애고 VStack에 배경색 추가
  AhnNyeong/AhnNyeong/UI/TargetViews/TargetMainView.swift
Labels: 🐛bug

#45 [feat][#36] 설정 화면 구현
  AhnNyeong/AhnNyeong.xcodeproj/project.pbxproj
  AhnNyeong/AhnNyeong/ContentView.swift
  AhnNyeong/AhnNyeong/GestureModifier.swift
  AhnNyeong/AhnNyeong/MVP/LoginTypeView.swift
  AhnNyeong/AhnNyeong/UI/SettingViews/DetailTermView.swift
  AhnNyeong/AhnNyeong/UI/SettingViews/OutCheckView.swift
  AhnNyeong/AhnNyeong/UI/SettingViews/SettingComponents.swift
  AhnNyeong/AhnNyeong/UI/SettingViews/SettingGuideView.swift
  AhnNyeong/AhnNyeong/UI/SettingViews/SettingMainView.swift
  AhnNyeong/AhnNyeong/UI/SettingViews/SettingNotiView.swift
  AhnNyeong/AhnNyeong/UI/SettingViews/SettingTermView.swift
Labels: ✨feature

#47 [feat][#40] 이용자 증상입력 뷰 구현
  AhnNyeong/AhnNyeong.xcodeproj/project.xcworkspace/xcuserdata/jaelyungkim.xcuserdatad/UserInterfaceState.xcuserstate
  AhnNyeong/AhnNyeong/Assets.xcassets/startDefault.imageset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/startDefault.imageset/startDefault.png
  AhnNyeong/AhnNyeong/Assets.xcassets/startPressed.imageset/Contents.json
  AhnNyeong/AhnNyeong/Assets.xcassets/startPressed.imageset/startPressed.png
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Mood/Mood1.imageset/Contents.json
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Mood/Mood1.imageset/Mood1.png
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Mood/Mood1.imageset/mood_happy_1x.png
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Mood/Mood2.imageset/Contents.json
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Mood/Mood2.imageset/Mood2.png
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Mood/Mood2.imageset/mood_normal_1x.png
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Mood/Mood3.imageset/Contents.json
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Mood/Mood3.imageset/Mood3.png
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Mood/Mood3.imageset/mood_bad_1x.png
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Symptom/Symp1.imageset/Contents.json
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Symptom/Symp1.imageset/Symp1.png
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Symptom/Symp1.imageset/cramp_none_1x.png
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Symptom/Symp2.imageset/Contents.json
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Symptom/Symp2.imageset/Symp2.png
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Symptom/Symp2.imageset/cramp_bad_1x.png
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Symptom/Symp3.imageset/Contents.json
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Symptom/Symp3.imageset/Symp3.png
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Symptom/Symp3.imageset/cramp_verybad_1x.png
  AhnNyeong/AhnNyeong/TargetMainView.swift
  AhnNyeong/AhnNyeong/TextModifier.swift
  AhnNyeong/AhnNyeong/UI/TargetViews/SympView.swift
  AhnNyeong/AhnNyeong/UI/TargetViews/TargetMainView.swift
Labels: ✨feature

#51 [feat][#48] 관리자 메인 뷰와 생리현황 뷰 구현 (+관리자 메인 달력 모달뷰)
  AhnNyeong/.swiftlint.yml
  AhnNyeong/AhnNyeong.xcodeproj/project.pbxproj
  AhnNyeong/AhnNyeong.xcodeproj/project.xcworkspace/xcuserdata/jaelyungkim.xcuserdatad/UserInterfaceState.xcuserstate
  AhnNyeong/AhnNyeong.xcodeproj/xcuserdata/jaelyungkim.xcuserdatad/xcschemes/xcschememanagement.plist
  AhnNyeong/AhnNyeong/AhnNyeongApp.swift
  AhnNyeong/AhnNyeong/EditView.swift
  AhnNyeong/AhnNyeong/LoFi/imper/EditView.swift
  AhnNyeong/AhnNyeong/LoFi/imper/MensInfoStore.swift
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Drop/Drop.imageset/Contents.json
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Drop/Drop.imageset/Drop.png
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Drop/DropFill.imageset/Contents.json
  AhnNyeong/AhnNyeong/Resources/Assets.xcassets/Image/Drop/DropFill.imageset/DropFill.png
  AhnNyeong/AhnNyeong/Resources/Color.swift
  AhnNyeong/AhnNyeong/Resources/Confetti_01.json
  AhnNyeong/AhnNyeong/Resources/Confetti_02.json
  AhnNyeong/AhnNyeong/TextModifier.swift
  AhnNyeong/AhnNyeong/UI/AdminViews/AdminMainView.swift
  AhnNyeong/AhnNyeong/UI/AdminViews/MensStatusView.swift
  AhnNyeong/AhnNyeong/UI/AdminViews/NextMensInfoView.swift
  AhnNyeong/AhnNyeong/UI/AdminViews/SampleAdminCalModalView.swift
  AhnNyeong/AhnNyeong/UI/AdminViews/TodayMensInfoView.swift
  AhnNyeong/AhnNyeong/UI/AdminViews/ToolbarBellView.swift
  AhnNyeong/AhnNyeong/UI/SettingViews/DetailTermView.swift
  AhnNyeong/AhnNyeong/UI/SettingViews/SettingMainView.swift
  AhnNyeong/AhnNyeong/UI/TargetViews/TargetMainView.swift
Labels: ✨feature

#53 [feat][#52] sprint7리뷰 후 발견한 버그 fix
  AhnNyeong/AhnNyeong.xcodeproj/project.pbxproj
  AhnNyeong/AhnNyeong/DeviceSize.swift
  AhnNyeong/AhnNyeong/UI/AdminViews/MensStatusView.swift
  AhnNyeong/AhnNyeong/UI/AdminViews/ToolbarBellView.swift
  AhnNyeong/AhnNyeong/UI/TargetViews/SympView.swift
  AhnNyeong/AhnNyeong/UI/TargetViews/TargetMainView.swift
Labels: 🐛bug
